// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/directoryapi/directory.proto

/*
Package directoryapi is a generated protocol buffer package.

It is generated from these files:
	pkg/directoryapi/directory.proto

It has these top-level messages:
	PutEntityRequest
	PutEntityResponse
	GetEntityRequest
	GetEntityResponse
	Entity
	Patient
	Office
*/
package directoryapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PutOperation int32

const (
	// new value was added
	PutOperation_STORED PutOperation = 0
	// value already existed
	PutOperation_LEFT_EXISTING PutOperation = 1
)

var PutOperation_name = map[int32]string{
	0: "STORED",
	1: "LEFT_EXISTING",
}
var PutOperation_value = map[string]int32{
	"STORED":        0,
	"LEFT_EXISTING": 1,
}

func (x PutOperation) String() string {
	return proto.EnumName(PutOperation_name, int32(x))
}
func (PutOperation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PutEntityRequest struct {
	Entity *Entity `protobuf:"bytes,1,opt,name=entity" json:"entity,omitempty"`
}

func (m *PutEntityRequest) Reset()                    { *m = PutEntityRequest{} }
func (m *PutEntityRequest) String() string            { return proto.CompactTextString(m) }
func (*PutEntityRequest) ProtoMessage()               {}
func (*PutEntityRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PutEntityRequest) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type PutEntityResponse struct {
	EntityId  string       `protobuf:"bytes,1,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	Operation PutOperation `protobuf:"varint,2,opt,name=operation,enum=directoryapi.PutOperation" json:"operation,omitempty"`
}

func (m *PutEntityResponse) Reset()                    { *m = PutEntityResponse{} }
func (m *PutEntityResponse) String() string            { return proto.CompactTextString(m) }
func (*PutEntityResponse) ProtoMessage()               {}
func (*PutEntityResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PutEntityResponse) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *PutEntityResponse) GetOperation() PutOperation {
	if m != nil {
		return m.Operation
	}
	return PutOperation_STORED
}

type GetEntityRequest struct {
	EntityId string `protobuf:"bytes,1,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
}

func (m *GetEntityRequest) Reset()                    { *m = GetEntityRequest{} }
func (m *GetEntityRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEntityRequest) ProtoMessage()               {}
func (*GetEntityRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetEntityRequest) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

type GetEntityResponse struct {
	Entity *Entity `protobuf:"bytes,1,opt,name=entity" json:"entity,omitempty"`
}

func (m *GetEntityResponse) Reset()                    { *m = GetEntityResponse{} }
func (m *GetEntityResponse) String() string            { return proto.CompactTextString(m) }
func (*GetEntityResponse) ProtoMessage()               {}
func (*GetEntityResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetEntityResponse) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type Entity struct {
	EntityId string `protobuf:"bytes,1,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	// Types that are valid to be assigned to AttributesType:
	//	*Entity_Patient
	//	*Entity_Office
	AttributesType isEntity_AttributesType `protobuf_oneof:"attributes_type"`
}

func (m *Entity) Reset()                    { *m = Entity{} }
func (m *Entity) String() string            { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()               {}
func (*Entity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type isEntity_AttributesType interface {
	isEntity_AttributesType()
}

type Entity_Patient struct {
	Patient *Patient `protobuf:"bytes,2,opt,name=patient,oneof"`
}
type Entity_Office struct {
	Office *Office `protobuf:"bytes,3,opt,name=office,oneof"`
}

func (*Entity_Patient) isEntity_AttributesType() {}
func (*Entity_Office) isEntity_AttributesType()  {}

func (m *Entity) GetAttributesType() isEntity_AttributesType {
	if m != nil {
		return m.AttributesType
	}
	return nil
}

func (m *Entity) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *Entity) GetPatient() *Patient {
	if x, ok := m.GetAttributesType().(*Entity_Patient); ok {
		return x.Patient
	}
	return nil
}

func (m *Entity) GetOffice() *Office {
	if x, ok := m.GetAttributesType().(*Entity_Office); ok {
		return x.Office
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Entity) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Entity_OneofMarshaler, _Entity_OneofUnmarshaler, _Entity_OneofSizer, []interface{}{
		(*Entity_Patient)(nil),
		(*Entity_Office)(nil),
	}
}

func _Entity_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Entity)
	// attributes_type
	switch x := m.AttributesType.(type) {
	case *Entity_Patient:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Patient); err != nil {
			return err
		}
	case *Entity_Office:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Office); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Entity.AttributesType has unexpected type %T", x)
	}
	return nil
}

func _Entity_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Entity)
	switch tag {
	case 2: // attributes_type.patient
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Patient)
		err := b.DecodeMessage(msg)
		m.AttributesType = &Entity_Patient{msg}
		return true, err
	case 3: // attributes_type.office
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Office)
		err := b.DecodeMessage(msg)
		m.AttributesType = &Entity_Office{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Entity_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Entity)
	// attributes_type
	switch x := m.AttributesType.(type) {
	case *Entity_Patient:
		s := proto.Size(x.Patient)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Entity_Office:
		s := proto.Size(x.Office)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Patient struct {
}

func (m *Patient) Reset()                    { *m = Patient{} }
func (m *Patient) String() string            { return proto.CompactTextString(m) }
func (*Patient) ProtoMessage()               {}
func (*Patient) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Office struct {
}

func (m *Office) Reset()                    { *m = Office{} }
func (m *Office) String() string            { return proto.CompactTextString(m) }
func (*Office) ProtoMessage()               {}
func (*Office) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*PutEntityRequest)(nil), "directoryapi.PutEntityRequest")
	proto.RegisterType((*PutEntityResponse)(nil), "directoryapi.PutEntityResponse")
	proto.RegisterType((*GetEntityRequest)(nil), "directoryapi.GetEntityRequest")
	proto.RegisterType((*GetEntityResponse)(nil), "directoryapi.GetEntityResponse")
	proto.RegisterType((*Entity)(nil), "directoryapi.Entity")
	proto.RegisterType((*Patient)(nil), "directoryapi.Patient")
	proto.RegisterType((*Office)(nil), "directoryapi.Office")
	proto.RegisterEnum("directoryapi.PutOperation", PutOperation_name, PutOperation_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Directory service

type DirectoryClient interface {
	PutEntity(ctx context.Context, in *PutEntityRequest, opts ...grpc.CallOption) (*PutEntityResponse, error)
	GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error)
}

type directoryClient struct {
	cc *grpc.ClientConn
}

func NewDirectoryClient(cc *grpc.ClientConn) DirectoryClient {
	return &directoryClient{cc}
}

func (c *directoryClient) PutEntity(ctx context.Context, in *PutEntityRequest, opts ...grpc.CallOption) (*PutEntityResponse, error) {
	out := new(PutEntityResponse)
	err := grpc.Invoke(ctx, "/directoryapi.Directory/PutEntity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryClient) GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error) {
	out := new(GetEntityResponse)
	err := grpc.Invoke(ctx, "/directoryapi.Directory/GetEntity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Directory service

type DirectoryServer interface {
	PutEntity(context.Context, *PutEntityRequest) (*PutEntityResponse, error)
	GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error)
}

func RegisterDirectoryServer(s *grpc.Server, srv DirectoryServer) {
	s.RegisterService(&_Directory_serviceDesc, srv)
}

func _Directory_PutEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryServer).PutEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/directoryapi.Directory/PutEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryServer).PutEntity(ctx, req.(*PutEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Directory_GetEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryServer).GetEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/directoryapi.Directory/GetEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryServer).GetEntity(ctx, req.(*GetEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Directory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "directoryapi.Directory",
	HandlerType: (*DirectoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutEntity",
			Handler:    _Directory_PutEntity_Handler,
		},
		{
			MethodName: "GetEntity",
			Handler:    _Directory_GetEntity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/directoryapi/directory.proto",
}

func init() { proto.RegisterFile("pkg/directoryapi/directory.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0x6d, 0xbf, 0x2f, 0x29, 0x74, 0x40, 0x6d, 0x37, 0x9a, 0x10, 0x4c, 0x94, 0xec, 0x89, 0x18,
	0x2d, 0xb1, 0x5e, 0x3c, 0xaa, 0xa1, 0x02, 0x89, 0x01, 0x52, 0x38, 0x78, 0x23, 0x05, 0x16, 0xb3,
	0x9a, 0x74, 0xd7, 0x76, 0x7a, 0xe0, 0xb7, 0xf8, 0x13, 0xfc, 0x93, 0xc6, 0x6e, 0x81, 0x52, 0x94,
	0xc4, 0xe3, 0xce, 0x7b, 0xf3, 0x66, 0xde, 0xbc, 0x85, 0x86, 0x7c, 0x7b, 0x69, 0xcd, 0x79, 0xc4,
	0x66, 0x28, 0xa2, 0x65, 0x20, 0xf9, 0xe6, 0xe1, 0xc8, 0x48, 0xa0, 0x20, 0xd5, 0x3c, 0x4a, 0xef,
	0xc0, 0x1a, 0x26, 0xe8, 0x85, 0xc8, 0x71, 0xe9, 0xb3, 0xf7, 0x84, 0xc5, 0x48, 0x2e, 0xc1, 0x60,
	0x69, 0xa1, 0xa6, 0x37, 0xf4, 0x66, 0xc5, 0x3d, 0x76, 0xf2, 0x2d, 0x4e, 0x46, 0xce, 0x38, 0xf4,
	0x15, 0xec, 0x9c, 0x42, 0x2c, 0x45, 0x18, 0x33, 0x72, 0x0a, 0xa6, 0x82, 0x27, 0x7c, 0x9e, 0xaa,
	0x98, 0x7e, 0x59, 0x15, 0x7a, 0x73, 0x72, 0x0b, 0xa6, 0x90, 0x2c, 0x0a, 0x90, 0x8b, 0xb0, 0xf6,
	0xaf, 0xa1, 0x37, 0x0f, 0xdd, 0xfa, 0xf6, 0x88, 0x61, 0x82, 0x83, 0x15, 0xc3, 0xdf, 0x90, 0x69,
	0x0b, 0xac, 0x0e, 0x2b, 0x6c, 0xbb, 0x6f, 0x14, 0xbd, 0x07, 0x3b, 0xd7, 0x90, 0x2d, 0xf7, 0x37,
	0x7f, 0x1f, 0x3a, 0x18, 0xaa, 0xb4, 0xdf, 0xd5, 0x35, 0x94, 0x64, 0x80, 0x9c, 0x85, 0x98, 0x7a,
	0xaa, 0xb8, 0x27, 0x05, 0x4f, 0x0a, 0xec, 0x6a, 0xfe, 0x8a, 0x47, 0x1c, 0x30, 0xc4, 0x62, 0xc1,
	0x67, 0xac, 0xf6, 0xff, 0xa7, 0x45, 0x06, 0x29, 0xd6, 0xd5, 0xfc, 0x8c, 0xf5, 0x60, 0xc3, 0x51,
	0x80, 0x18, 0xf1, 0x69, 0x82, 0x2c, 0x9e, 0xe0, 0x52, 0x32, 0x6a, 0x42, 0x29, 0x13, 0xa6, 0x65,
	0x30, 0x54, 0xc7, 0xc5, 0x15, 0x54, 0xf3, 0x17, 0x24, 0x00, 0xc6, 0x68, 0x3c, 0xf0, 0xbd, 0xb6,
	0xa5, 0x11, 0x1b, 0x0e, 0x9e, 0xbc, 0xc7, 0xf1, 0xc4, 0x7b, 0xee, 0x8d, 0xc6, 0xbd, 0x7e, 0xc7,
	0xd2, 0xdd, 0x4f, 0x1d, 0xcc, 0xf6, 0x6a, 0x30, 0xe9, 0x83, 0xb9, 0xce, 0x93, 0x9c, 0xed, 0xe4,
	0xb2, 0x75, 0xfc, 0xfa, 0xf9, 0xaf, 0xb8, 0xba, 0x35, 0xd5, 0xbe, 0xf5, 0xd6, 0x11, 0x14, 0xf5,
	0x8a, 0x61, 0x16, 0xf5, 0x76, 0xb2, 0xa3, 0xda, 0xd4, 0x48, 0xbf, 0xf1, 0xcd, 0x57, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xfb, 0xfd, 0xab, 0x3e, 0xea, 0x02, 0x00, 0x00,
}
