// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/directoryapi/directory.proto

/*
Package directoryapi is a generated protocol buffer package.

It is generated from these files:
	pkg/directoryapi/directory.proto

It has these top-level messages:
	PutEntityRequest
	PutEntityResponse
	GetEntityRequest
	GetEntityResponse
	SearchEntityRequest
	SearchEntityResponse
	Entity
	Patient
	Office
	Date
*/
package directoryapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PutEntityRequest struct {
	Entity *Entity `protobuf:"bytes,1,opt,name=entity" json:"entity,omitempty"`
}

func (m *PutEntityRequest) Reset()                    { *m = PutEntityRequest{} }
func (m *PutEntityRequest) String() string            { return proto.CompactTextString(m) }
func (*PutEntityRequest) ProtoMessage()               {}
func (*PutEntityRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PutEntityRequest) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type PutEntityResponse struct {
	EntityId string `protobuf:"bytes,1,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
}

func (m *PutEntityResponse) Reset()                    { *m = PutEntityResponse{} }
func (m *PutEntityResponse) String() string            { return proto.CompactTextString(m) }
func (*PutEntityResponse) ProtoMessage()               {}
func (*PutEntityResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PutEntityResponse) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

type GetEntityRequest struct {
	EntityId string `protobuf:"bytes,1,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
}

func (m *GetEntityRequest) Reset()                    { *m = GetEntityRequest{} }
func (m *GetEntityRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEntityRequest) ProtoMessage()               {}
func (*GetEntityRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetEntityRequest) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

type GetEntityResponse struct {
	Entity *Entity `protobuf:"bytes,1,opt,name=entity" json:"entity,omitempty"`
}

func (m *GetEntityResponse) Reset()                    { *m = GetEntityResponse{} }
func (m *GetEntityResponse) String() string            { return proto.CompactTextString(m) }
func (*GetEntityResponse) ProtoMessage()               {}
func (*GetEntityResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetEntityResponse) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type SearchEntityRequest struct {
	Query string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	Limit uint32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (m *SearchEntityRequest) Reset()                    { *m = SearchEntityRequest{} }
func (m *SearchEntityRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchEntityRequest) ProtoMessage()               {}
func (*SearchEntityRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SearchEntityRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchEntityRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type SearchEntityResponse struct {
	Entities []*Entity `protobuf:"bytes,1,rep,name=entities" json:"entities,omitempty"`
}

func (m *SearchEntityResponse) Reset()                    { *m = SearchEntityResponse{} }
func (m *SearchEntityResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchEntityResponse) ProtoMessage()               {}
func (*SearchEntityResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SearchEntityResponse) GetEntities() []*Entity {
	if m != nil {
		return m.Entities
	}
	return nil
}

type Entity struct {
	EntityId string `protobuf:"bytes,1,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	// Types that are valid to be assigned to TypeAttributes:
	//	*Entity_Patient
	//	*Entity_Office
	TypeAttributes isEntity_TypeAttributes `protobuf_oneof:"type_attributes"`
}

func (m *Entity) Reset()                    { *m = Entity{} }
func (m *Entity) String() string            { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()               {}
func (*Entity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type isEntity_TypeAttributes interface {
	isEntity_TypeAttributes()
}

type Entity_Patient struct {
	Patient *Patient `protobuf:"bytes,2,opt,name=patient,oneof"`
}
type Entity_Office struct {
	Office *Office `protobuf:"bytes,3,opt,name=office,oneof"`
}

func (*Entity_Patient) isEntity_TypeAttributes() {}
func (*Entity_Office) isEntity_TypeAttributes()  {}

func (m *Entity) GetTypeAttributes() isEntity_TypeAttributes {
	if m != nil {
		return m.TypeAttributes
	}
	return nil
}

func (m *Entity) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *Entity) GetPatient() *Patient {
	if x, ok := m.GetTypeAttributes().(*Entity_Patient); ok {
		return x.Patient
	}
	return nil
}

func (m *Entity) GetOffice() *Office {
	if x, ok := m.GetTypeAttributes().(*Entity_Office); ok {
		return x.Office
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Entity) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Entity_OneofMarshaler, _Entity_OneofUnmarshaler, _Entity_OneofSizer, []interface{}{
		(*Entity_Patient)(nil),
		(*Entity_Office)(nil),
	}
}

func _Entity_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Entity)
	// type_attributes
	switch x := m.TypeAttributes.(type) {
	case *Entity_Patient:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Patient); err != nil {
			return err
		}
	case *Entity_Office:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Office); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Entity.TypeAttributes has unexpected type %T", x)
	}
	return nil
}

func _Entity_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Entity)
	switch tag {
	case 2: // type_attributes.patient
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Patient)
		err := b.DecodeMessage(msg)
		m.TypeAttributes = &Entity_Patient{msg}
		return true, err
	case 3: // type_attributes.office
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Office)
		err := b.DecodeMessage(msg)
		m.TypeAttributes = &Entity_Office{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Entity_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Entity)
	// type_attributes
	switch x := m.TypeAttributes.(type) {
	case *Entity_Patient:
		s := proto.Size(x.Patient)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Entity_Office:
		s := proto.Size(x.Office)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Patient struct {
	LastName   string `protobuf:"bytes,1,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	FirstName  string `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	MiddleName string `protobuf:"bytes,3,opt,name=middle_name,json=middleName" json:"middle_name,omitempty"`
	Suffix     string `protobuf:"bytes,4,opt,name=suffix" json:"suffix,omitempty"`
	Birthdate  *Date  `protobuf:"bytes,5,opt,name=birthdate" json:"birthdate,omitempty"`
}

func (m *Patient) Reset()                    { *m = Patient{} }
func (m *Patient) String() string            { return proto.CompactTextString(m) }
func (*Patient) ProtoMessage()               {}
func (*Patient) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Patient) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Patient) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Patient) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *Patient) GetSuffix() string {
	if m != nil {
		return m.Suffix
	}
	return ""
}

func (m *Patient) GetBirthdate() *Date {
	if m != nil {
		return m.Birthdate
	}
	return nil
}

type Office struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Office) Reset()                    { *m = Office{} }
func (m *Office) String() string            { return proto.CompactTextString(m) }
func (*Office) ProtoMessage()               {}
func (*Office) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Office) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Date struct {
	Year  uint32 `protobuf:"varint,1,opt,name=year" json:"year,omitempty"`
	Month uint32 `protobuf:"varint,2,opt,name=month" json:"month,omitempty"`
	Day   uint32 `protobuf:"varint,3,opt,name=day" json:"day,omitempty"`
}

func (m *Date) Reset()                    { *m = Date{} }
func (m *Date) String() string            { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()               {}
func (*Date) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Date) GetYear() uint32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Date) GetMonth() uint32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Date) GetDay() uint32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func init() {
	proto.RegisterType((*PutEntityRequest)(nil), "directoryapi.PutEntityRequest")
	proto.RegisterType((*PutEntityResponse)(nil), "directoryapi.PutEntityResponse")
	proto.RegisterType((*GetEntityRequest)(nil), "directoryapi.GetEntityRequest")
	proto.RegisterType((*GetEntityResponse)(nil), "directoryapi.GetEntityResponse")
	proto.RegisterType((*SearchEntityRequest)(nil), "directoryapi.SearchEntityRequest")
	proto.RegisterType((*SearchEntityResponse)(nil), "directoryapi.SearchEntityResponse")
	proto.RegisterType((*Entity)(nil), "directoryapi.Entity")
	proto.RegisterType((*Patient)(nil), "directoryapi.Patient")
	proto.RegisterType((*Office)(nil), "directoryapi.Office")
	proto.RegisterType((*Date)(nil), "directoryapi.Date")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Directory service

type DirectoryClient interface {
	PutEntity(ctx context.Context, in *PutEntityRequest, opts ...grpc.CallOption) (*PutEntityResponse, error)
	GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error)
	SearchEntity(ctx context.Context, in *SearchEntityRequest, opts ...grpc.CallOption) (*SearchEntityResponse, error)
}

type directoryClient struct {
	cc *grpc.ClientConn
}

func NewDirectoryClient(cc *grpc.ClientConn) DirectoryClient {
	return &directoryClient{cc}
}

func (c *directoryClient) PutEntity(ctx context.Context, in *PutEntityRequest, opts ...grpc.CallOption) (*PutEntityResponse, error) {
	out := new(PutEntityResponse)
	err := grpc.Invoke(ctx, "/directoryapi.Directory/PutEntity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryClient) GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error) {
	out := new(GetEntityResponse)
	err := grpc.Invoke(ctx, "/directoryapi.Directory/GetEntity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryClient) SearchEntity(ctx context.Context, in *SearchEntityRequest, opts ...grpc.CallOption) (*SearchEntityResponse, error) {
	out := new(SearchEntityResponse)
	err := grpc.Invoke(ctx, "/directoryapi.Directory/SearchEntity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Directory service

type DirectoryServer interface {
	PutEntity(context.Context, *PutEntityRequest) (*PutEntityResponse, error)
	GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error)
	SearchEntity(context.Context, *SearchEntityRequest) (*SearchEntityResponse, error)
}

func RegisterDirectoryServer(s *grpc.Server, srv DirectoryServer) {
	s.RegisterService(&_Directory_serviceDesc, srv)
}

func _Directory_PutEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryServer).PutEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/directoryapi.Directory/PutEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryServer).PutEntity(ctx, req.(*PutEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Directory_GetEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryServer).GetEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/directoryapi.Directory/GetEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryServer).GetEntity(ctx, req.(*GetEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Directory_SearchEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryServer).SearchEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/directoryapi.Directory/SearchEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryServer).SearchEntity(ctx, req.(*SearchEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Directory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "directoryapi.Directory",
	HandlerType: (*DirectoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutEntity",
			Handler:    _Directory_PutEntity_Handler,
		},
		{
			MethodName: "GetEntity",
			Handler:    _Directory_GetEntity_Handler,
		},
		{
			MethodName: "SearchEntity",
			Handler:    _Directory_SearchEntity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/directoryapi/directory.proto",
}

func init() { proto.RegisterFile("pkg/directoryapi/directory.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 483 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x8d, 0x93, 0xd4, 0xfd, 0x3c, 0x69, 0xf4, 0x25, 0x4b, 0x40, 0x56, 0xf9, 0x69, 0xd8, 0xab,
	0x5e, 0xa0, 0x34, 0x84, 0x17, 0xa0, 0x55, 0x11, 0xe1, 0xa6, 0x54, 0xe6, 0x82, 0xcb, 0x68, 0x13,
	0x8f, 0xc9, 0x8a, 0xf8, 0xa7, 0xeb, 0xb1, 0x84, 0xef, 0x79, 0x0b, 0x5e, 0x82, 0x47, 0x44, 0xde,
	0xb5, 0x53, 0xdb, 0xb4, 0x91, 0xb8, 0xdb, 0x99, 0x73, 0xe6, 0xec, 0x19, 0xef, 0x8c, 0x61, 0x9a,
	0x7c, 0xff, 0x76, 0xe1, 0x4b, 0x85, 0x1b, 0x8a, 0x55, 0x2e, 0x12, 0x79, 0x1f, 0xcc, 0x12, 0x15,
	0x53, 0xcc, 0x4e, 0xea, 0x28, 0x7f, 0x0f, 0xa3, 0xdb, 0x8c, 0x3e, 0x44, 0x24, 0x29, 0xf7, 0xf0,
	0x2e, 0xc3, 0x94, 0xd8, 0x1b, 0xb0, 0x51, 0x27, 0x5c, 0x6b, 0x6a, 0x9d, 0x0f, 0x16, 0x93, 0x59,
	0xbd, 0x64, 0x56, 0x92, 0x4b, 0x0e, 0x9f, 0xc3, 0xb8, 0xa6, 0x90, 0x26, 0x71, 0x94, 0x22, 0x7b,
	0x0e, 0x8e, 0x81, 0x57, 0xd2, 0xd7, 0x2a, 0x8e, 0xf7, 0x9f, 0x49, 0x7c, 0xf2, 0xf9, 0x05, 0x8c,
	0x3e, 0x62, 0xeb, 0xce, 0x83, 0x05, 0x97, 0x30, 0xae, 0x15, 0x94, 0x57, 0xfc, 0x9b, 0xcb, 0x4b,
	0x78, 0xf2, 0x05, 0x85, 0xda, 0x6c, 0x9b, 0xd7, 0x4e, 0xe0, 0xe8, 0x2e, 0x43, 0x95, 0x97, 0x57,
	0x9a, 0xa0, 0xc8, 0xee, 0x64, 0x28, 0xc9, 0xed, 0x4e, 0xad, 0xf3, 0xa1, 0x67, 0x02, 0xbe, 0x84,
	0x49, 0x53, 0xa2, 0x34, 0x32, 0x07, 0xe3, 0x54, 0x62, 0xea, 0x5a, 0xd3, 0xde, 0xa3, 0x56, 0xf6,
	0x2c, 0xfe, 0xcb, 0x02, 0xdb, 0x24, 0x0f, 0xf6, 0xcd, 0xde, 0xc2, 0x71, 0x22, 0x48, 0x62, 0x64,
	0x9c, 0x0c, 0x16, 0x4f, 0x9b, 0xc2, 0xb7, 0x06, 0x5c, 0x76, 0xbc, 0x8a, 0xc7, 0x66, 0x60, 0xc7,
	0x41, 0x20, 0x37, 0xe8, 0xf6, 0x1e, 0xfa, 0x2a, 0x9f, 0x35, 0xb6, 0xec, 0x78, 0x25, 0xeb, 0x6a,
	0x0c, 0xff, 0x53, 0x9e, 0xe0, 0x4a, 0x10, 0x29, 0xb9, 0xce, 0x08, 0x53, 0xfe, 0xdb, 0x82, 0xe3,
	0x52, 0xb9, 0xb0, 0xb7, 0x13, 0x29, 0xad, 0x22, 0x11, 0x62, 0x65, 0xaf, 0x48, 0xdc, 0x88, 0x10,
	0xd9, 0x4b, 0x80, 0x40, 0xaa, 0x0a, 0xed, 0x6a, 0xd4, 0xd1, 0x19, 0x0d, 0x9f, 0xc1, 0x20, 0x94,
	0xbe, 0xbf, 0x43, 0x83, 0xf7, 0x34, 0x0e, 0x26, 0xa5, 0x09, 0xcf, 0xc0, 0x4e, 0xb3, 0x20, 0x90,
	0x3f, 0xdc, 0xbe, 0xc6, 0xca, 0x88, 0xcd, 0xc1, 0x59, 0x4b, 0x45, 0x5b, 0x5f, 0x10, 0xba, 0x47,
	0xba, 0x0d, 0xd6, 0x6c, 0xe3, 0x5a, 0x10, 0x7a, 0xf7, 0x24, 0xfe, 0x02, 0x6c, 0xd3, 0x19, 0x63,
	0xd0, 0xaf, 0x79, 0xd5, 0x67, 0x7e, 0x05, 0xfd, 0xa2, 0xa0, 0xc0, 0x72, 0x14, 0x4a, 0x63, 0x43,
	0x4f, 0x9f, 0x8b, 0xa7, 0x0e, 0xe3, 0x88, 0xb6, 0xd5, 0x53, 0xeb, 0x80, 0x8d, 0xa0, 0xe7, 0x8b,
	0x5c, 0x5b, 0x1e, 0x7a, 0xc5, 0x71, 0xf1, 0xb3, 0x0b, 0xce, 0x75, 0x65, 0x81, 0xdd, 0x80, 0xb3,
	0x9f, 0x79, 0xf6, 0xaa, 0xf5, 0x28, 0xad, 0x75, 0x3a, 0x3d, 0x7b, 0x14, 0x37, 0x03, 0xc4, 0x3b,
	0x85, 0xde, 0x7e, 0xc0, 0xdb, 0x7a, 0xed, 0x55, 0x69, 0xeb, 0xfd, 0xb5, 0x19, 0xbc, 0xc3, 0xbe,
	0xc2, 0x49, 0x7d, 0x54, 0xd9, 0xeb, 0x66, 0xc9, 0x03, 0x9b, 0x70, 0xca, 0x0f, 0x51, 0x2a, 0xe1,
	0xb5, 0xad, 0xff, 0x21, 0xef, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xda, 0xa3, 0x57, 0x07, 0x67,
	0x04, 0x00, 0x00,
}
