version: 2
jobs:
  build:
    docker:
      - image: gcr.io/elxir-core-infra/service-base-build:latest
        auth:
          username: _json_key
          password: ${GCR_SVC_JSON}
    parallelism: 1
    working_directory: /go/src/github.com/elxirhealth/directory
    steps:
      - run: git config --global core.autocrlf input
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - arch={{ arch }}-vendor={{ checksum "Gopkg.lock" }}-v1
            - arch={{ arch }}-vendor={{ checksum "Gopkg.lock" }}
            - arch={{ arch }}
      - run: make get-deps
      - save_cache:
          key: arch={{ arch }}-vendor={{ checksum "Gopkg.lock" }}-v1
          paths:
            - vendor
      - run: make build
      - run: make build-static
      - run: make docker-image
      - run: make test
      - run: make lint
      - run: make acceptance
      - run: make demo
